global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer"
    static_configs:
      - targets: ["orderer.example.com:9443"]
  - job_name: "peer0_mngorg"
    static_configs:
      - targets: ["peer0.mngorg.example.com:9444"]
  - job_name: "peer1_mngorg"
    static_configs:
      - targets: ["peer1.mngorg.example.com:9444"]
  - job_name: "peer2_mngorg"
    static_configs:
      - targets: ["peer2.mngorg.example.com:9444"]
  - job_name: "peer3_mngorg"
    static_configs:
      - targets: ["peer3.mngorg.example.com:9444"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
